#+TITLE: Zeus
#+DESCRIPTION: Zeus is the easiest way to install and operate a Bitcoin Core node.
#+AUTHOR: mike.rosset@gmail.com
#+STARTUP: overview

The easiest way to install and operate a Bitcoin Core node.

* Install Zeus
#+begin_src sh
  go install github.com/mrosset/zeus
  #+end_src

#+RESULTS:

* Installing Bitcoin Core with Zeus
To install bitcoind to it's default location of $HOME/bitcoin run.
#+begin_src sh
  zeus install
#+end_src

If you would like to install bitcoin to another location. Use the --prefix flag
#+begin_src sh
zeus --prefix=/opt/bitcoin install
#+end_src

** Experimental
To install Bitcoin Core and Lighting Network Node
#+begin_src sh
zeus install -l
#+end_src

* License

Zeus is published under the [[https://www.gnu.org/licenses/gpl-3.0.html][GNU GPLv3 license]] or any later
version.

Zeus is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

Zeus is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Org mode.  If not, see https://www.gnu.org/licenses/.
