#+TITLE: Zeus
#+DESCRIPTION: Zeus. The easiest way to install and operate a Bitcoin full node.
#+AUTHOR: mike.rosset@gmail.com
#+STARTUP: overview

Is a unofficial installer for Bitcoin. Using Zeus you can download,
install and have a running Bitcoin full node or wallet in just
minutes.

* Status

Though Zeus works at this time. It's still early in development and is
considered in alpha state. Any current releases are for developer
consideration only and not for production use.

** Supported CPU and Operating Systems

Zeus should work on any architect and operating system supported by [[https://go.dev/][Go]]
and [[https://bitcoincore.org/][Bitcoin]].

Currently supported CPUs and OSs
*** Linux
- x86_64 (amd64)
- aarch64 (arm64)
- ppc64le

More targets should be supported soon. If you have a target that you
would like supported. Please create an [[https://github.com/mrosset/zeus/issues][Issue]]


* Building from Source
** Dependencies
This only requirement for building from source is a working [[https://go.dev/][Go]] distribution.

* Installing Zeus

There are no binary releases yet. But you can quickly install with Go using.
#+begin_src sh
  go install github.com/mrosset/zeus
#+end_src

#+RESULTS:

The build form source tree you can use.
#+begin_src sh
  git clone https://github.com/mrosset/zeus
  cd zeus
  go install
#+end_src

#+RESULTS:

* Using Zeus

To install Bitcoin to it's default location of $HOME/bitcoin .
#+begin_src sh
  zeus install
#+end_src

This will download and verify the Bitcoin binaries from [[https://bitcoincore.org/en/download/][Bitcoin Core
Downloads]]

If you would like to install bitcoin to another location. Use the --prefix flag
#+begin_src sh
zeus --prefix=/opt/bitcoin install
#+end_src

This will download and verify the Lighting Network Daemon binaries
from [[https://github.com/lightningnetwork/lnd/releases][Lightning Releases]]

** Experimental

To install Bitcoin Core and Lighting Network Node
#+begin_src sh
zeus install -l
#+end_src

* License

Zeus is published under the [[https://www.gnu.org/licenses/gpl-3.0.html][GNU GPLv3 license]] or any later
version.

Zeus is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

Zeus is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Org mode.  If not, see https://www.gnu.org/licenses/.
